# auto: true

markdown: rdiscount
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8

title: Taotao's Zone
url: http://litaotao.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/">taotaoli</a>

myblog:
  gavatar: images/1.jpg
  gpname: litaotao
  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/litaotao
  email: mailto:litaotao@vip.163.com
  coverimgs: []
  postbgimg: []

prose:
  rooturl: "_posts"
  siteurl: "http://litaotao.github.io/"
  media: "images"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "published"
        field:
          element: "hidden"
          value: "true"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
